import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const formatDate = (d) =>
  d ? new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '-';

const safeFilePart = (s) => String(s ?? 'invoice').replace(/[^\w-]/g, '_');

/**
 * Build a sale/purchase invoice PDF and trigger download.
 * Uses ASCII-friendly currency labels for reliable built-in font rendering.
 */
export const downloadInvoicePdf = ({ invoice, fallbackDoc, type = 'sale' }) => {
  const doc = invoice || fallbackDoc;
  if (!doc) return;

  const isSale = type === 'sale';
  const number = invoice?.invoiceNumber || doc?._id || 'invoice';
  const date = formatDate(invoice?.invoiceDate || doc?.saleDate || doc?.purchaseDate);
  const party = isSale
    ? invoice?.customerName || doc?.customerName || '-'
    : invoice?.supplierName || doc?.supplierName || '-';
  const items = invoice?.items || doc?.items || [];
  const total = isSale
    ? Number(invoice?.totalAmount ?? doc?.totalAmount ?? 0)
    : Number(invoice?.totalCost ?? doc?.totalCost ?? 0);

  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = pdf.internal.pageSize.getWidth();
  const margin = 14;
  let y = 18;

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  pdf.setTextColor(37, 99, 235);
  pdf.text('Invenzaa', margin, y);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Pharmacy inventory', pageW - margin, y, { align: 'right' });

  y += 10;
  pdf.setTextColor(15, 23, 42);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(isSale ? 'Sales invoice' : 'Purchase invoice', margin, y);

  y += 8;
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text(`Invoice no: ${number}`, margin, y);
  pdf.text(`Date: ${date}`, margin, y + 5);
  pdf.text(`${isSale ? 'Customer' : 'Supplier'}: ${party}`, margin, y + 10);

  const body = items.map((it, idx) => {
    const name = String(it.medicineName || it.medicine?.name || 'Unknown');
    const batch = String(it.batchNo || it.batch?.batchNo || '-');
    const qty = Number(it.quantity || 0);
    const unit = Number(isSale ? it.unitPrice : it.unitCost || 0);
    const lineTotal = Number(it.total ?? qty * unit);
    return [
      String(idx + 1),
      name,
      batch,
      String(qty),
      unit.toFixed(2),
      lineTotal.toFixed(2),
    ];
  });

  autoTable(pdf, {
    startY: y + 16,
    head: [['#', 'Item', 'Batch', 'Qty', 'Unit (INR)', 'Total (INR)']],
    body: body.length ? body : [['-', 'No line items', '-', '-', '-', '-']],
    theme: 'striped',
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    styles: { fontSize: 9, cellPadding: 2.5, textColor: [30, 41, 59] },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 58 },
      2: { cellWidth: 28 },
      3: { cellWidth: 16, halign: 'right' },
      4: { cellWidth: 24, halign: 'right' },
      5: { cellWidth: 28, halign: 'right' },
    },
    margin: { left: margin, right: margin },
  });

  const tableEnd = pdf.lastAutoTable?.finalY ?? y + 40;
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor(15, 23, 42);
  pdf.text(`Grand total: INR ${total.toFixed(2)}`, pageW - margin, tableEnd + 12, { align: 'right' });

  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(8);
  pdf.setTextColor(148, 163, 184);
  pdf.text('Generated by Invenzaa', pageW / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' });

  const fname = `${isSale ? 'sale' : 'purchase'}-invoice-${safeFilePart(number)}.pdf`;
  pdf.save(fname);
};

/** @deprecated Use downloadInvoicePdf — kept as alias for older imports */
export const downloadInvoiceTxt = downloadInvoicePdf;
